apiVersion: v1
kind: Service
metadata:
  name: icarrental-service
spec:
  selector:
    app: icarrental
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort